/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneynormalizeStyle {
    }
    interface HoneyStyle {
        /**
          * Get the current theme as string in lowercase of tag name.
         */
        "getTheme": () => Promise<string>;
    }
}
declare global {
    interface HTMLHoneynormalizeStyleElement extends Components.HoneynormalizeStyle, HTMLStencilElement {
    }
    var HTMLHoneynormalizeStyleElement: {
        prototype: HTMLHoneynormalizeStyleElement;
        new (): HTMLHoneynormalizeStyleElement;
    };
    interface HTMLHoneyStyleElement extends Components.HoneyStyle, HTMLStencilElement {
    }
    var HTMLHoneyStyleElement: {
        prototype: HTMLHoneyStyleElement;
        new (): HTMLHoneyStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-normalize-style": HTMLHoneynormalizeStyleElement;
        "honey-style": HTMLHoneyStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneynormalizeStyle {
    }
    interface HoneyStyle {
    }
    interface IntrinsicElements {
        "honey-normalize-style": HoneynormalizeStyle;
        "honey-style": HoneyStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-normalize-style": LocalJSX.HoneynormalizeStyle & JSXBase.HTMLAttributes<HTMLHoneynormalizeStyleElement>;
            "honey-style": LocalJSX.HoneyStyle & JSXBase.HTMLAttributes<HTMLHoneyStyleElement>;
        }
    }
}
