/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HoneyNormalizeStyle {
    }
}
declare global {
    interface HTMLHoneyNormalizeStyleElement extends Components.HoneyNormalizeStyle, HTMLStencilElement {
    }
    var HTMLHoneyNormalizeStyleElement: {
        prototype: HTMLHoneyNormalizeStyleElement;
        new (): HTMLHoneyNormalizeStyleElement;
    };
    interface HTMLElementTagNameMap {
        "honey-normalize-style": HTMLHoneyNormalizeStyleElement;
    }
}
declare namespace LocalJSX {
    interface HoneyNormalizeStyle {
    }
    interface IntrinsicElements {
        "honey-normalize-style": HoneyNormalizeStyle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-normalize-style": LocalJSX.HoneyNormalizeStyle & JSXBase.HTMLAttributes<HTMLHoneyNormalizeStyleElement>;
        }
    }
}
